version: "2"

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./test
      dockerfile: Dockerfile
    depends_on:
      - $$app_slug$$db
      - $$app_slug$$
      - $$app_slug$$nginx
    volumes_from:
      - $$app_slug$$
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  $$app_slug$$:
    # For development or CI, tag build from local Dockerfile
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
        - TAG=${TAG}
        - VCS_REF=${VCS_REF}
        - BUILD_DATE=${BUILD_DATE}
    # For production, download prebuilt image
    image: ${IMAGE_NAME}
    container_name: $$app_slug$$
    #restart: always
    depends_on:
      - $$app_slug$$db
    links:
      - $$app_slug$$db
    #ports:
    #  - 9000:9000
    volumes:
      - /srv/$$app_slug$$/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - $$app_uppercase_slug$$_DB_TYPE=pgsql
      - $$app_uppercase_slug$$_DB_HOST=$$app_slug$$db # same as pgsql container name
      - $$app_uppercase_slug$$_DB_NAME=$$app_slug$$ # same as pgsql POSTGRES_DB env name
      - $$app_uppercase_slug$$_DB_USER=$$app_slug$$ # same as pgsql POSTGRES_USER env name
      - $$app_uppercase_slug$$_DB_PASSWORD=$$app_slug$$ # same as pgsql POSTGRES_PASSWORD env name

  $$app_slug$$db:
    image: postgres:latest
    container_name: $$app_slug$$db
    restart: always
    #ports:
    #  - 5432:5432
    volumes:
      - /srv/$$app_slug$$/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - POSTGRES_DB=$$app_slug$$
      - POSTGRES_USER=$$app_slug$$
      - POSTGRES_PASSWORD=$$app_slug$$

  $$app_slug$$nginx:
    image: nginx:latest
    container_name: $$app_slug$$nginx
    restart: always
    ports:
      - 80:80
      # If you need SSL connection
      # - '443:443'
    depends_on:
      - $$app_slug$$
    links:
      - $$app_slug$$
    volumes:
      - /srv/$$app_slug$$/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # TODO Provide a custom nginx conf
      #- ./nginx.conf:/etc/nginx/nginx.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    environment:
      - NGINX_HOST=localhost # set your local domain or your live domain
      # - NGINX_CGI=$$app_slug$$:9000 # same as $$app_slug$$ container name
